### ISSUE TITLE
Russian letters

### ISSUE THREAD

**Issue by AlekseyMS** [micropython-Chinese-Community/mpy-lib#11]
Hello. How do I add a display of Russian letters?

**Comment by shaoziyang** [comment]
First you need a Russian font, usually we use a dot matrix font of equal width. When it needs to be displayed, read the font file and display it. In some cases, font files need to be converted for quick display.

**Comment by AlekseyMS** [comment]
The display supports Russian letters. I attach the documentation. For some reason, there is an offset of 10 characters according to the table on page 9. For example, I enter the letter "ц", the display outputs "F". Can set the offset somehow. The display is slightly different, but it works similarly to the 1602
[MT-20S4M_en LCD.pdf](https://github.com/micropython-Chinese-Community/mpy-lib/files/7710748/MT-20S4M_en.LCD.pdf)
.

**Comment by AlekseyMS** [comment]
Or tell me another solution. Thanks

**Comment by shaoziyang** [comment]
MT-20S4M is similar to LCD1602, but with two build font pages. In every page, 0x20-0x7A is normal char, same as LCD1602, Russian char in high area. I think you may display Russian letters by write corresponding code to ram. 

1. Set DDRAM Address
2. Write Data to RAM

**Comment by AlekseyMS** [comment]
Can you write how it will look in the code? Interested in modifying the library to work with the display 2004
