### ISSUE TITLE
Line 36 in lib calls time.sleep_ms, but imports as "from time import sleep_ms"

### ISSUE THREAD

**Issue by AndyThirtover** [micropython-Chinese-Community/mpy-lib#5]
Line 36 of mp_i2c_lcd1602.py gives an error of time not defined.

Since Micropython 1.13, it would be better for line 10 to read:
from utime import sleep_ms

and line 36:
sleep_ms(1)

test.py could have a better I2C definition, for example

i2c = I2C(0, scl=Pin(22), sda=(Pin(21), freq=400000)
LCD = LCD1602(i2c, addr=39)

This is how I got this working.

**Comment by shaoziyang** [comment]
Thanks.
