### ISSUE TITLE
Problem with the alarm

### ISSUE THREAD

**Issue by GeralDennis** [micropython-Chinese-Community/mpy-lib#9]
Hi
I' ve had some problems with the following lines of code:
ds.ALARM(12, 20, 10, ds.PER_DISABLE)
ds.ALARM(12, 20, 10, ds.PER_DAY)
When I run the programan, the shell show me the following:
-----AttributeError: 'DS3231' object has no attribute 'PER_DISABLE'---
I am using an ESP32 dev module
Could you help me fix it?
Thank you very much in advance.

**Comment by shaoziyang** [comment]
Sorry, this is an error in the demo program. Please use the following usage:
```
ds.ALARM(12, 20, 10, DS3231.PER_DISABLE)
ds.ALARM(12, 20, 10, DS3231.PER_DAY)
```

**Comment by GeralDennis** [comment]
Thanks for your help ¡¡¡¡¡¡¡
